DefaultContentLanguage = "en"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://gohugo-theme-ananke.pages.dev"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
resourceDir = "../resources"
theme = "ananke"
title = "Test"
[languages.en]
contentDir = "content/en"
title = "Ananke"
weight = 1
[languages.fr]
contentDir = "content/fr"
title = "Ananke Fr"
weight = 2
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
author = ""
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
favicon = ""
recent_posts_number = 3
site_logo = ""
text_color = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
